# Generated by Django 4.1.3 on 2022-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0002_remove_marvel_comicsname_remove_marvel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvel',
            name='charactername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
