# Generated by Django 4.1.3 on 2022-11-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0004_alter_marvel_charactername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marvel',
            old_name='charactername',
            new_name='character_name',
        ),
    ]
