# Generated by Django 4.1.3 on 2022-11-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0005_rename_charactername_marvel_character_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marvel',
            old_name='character_name',
            new_name='char_name',
        ),
    ]
