# Generated by Django 4.1.3 on 2022-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0006_rename_character_name_marvel_char_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvel',
            name='char_name',
        ),
        migrations.AddField(
            model_name='marvel',
            name='character',
            field=models.CharField(default='', max_length=200),
        ),
    ]
